gameCoop/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^accounts/', include('allauth.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^vote/', include('vote.urls')),
    url(r'^org_work/', include('org_work.urls')),
    url(r'^org_struct/', include('org_struct.urls')),
    url(r'^org_home/', include('org_home.urls')),
    url(r'^activity_feed/', include('activity_feed.urls')),
    url(r'^user_profiles/', include('user_profiles.urls')),
    url(r'^discuss/', include('discuss.urls')),
    url(r'^home/', include('home.urls')),
    url(r'^home/', include('home.urls')),
    url(r'^consensusEditing/', include('consensusEditing.urls')),
]

home/urls.py
from django.conf.urls import url
from . import views

app_name = 'home'

urlpatterns = [
    # url(r'^$', views.IndexView, name='index'),
    url(r'^$', views.OrganizationView, name='index'),

    url(r'^organizations', views.OrganizationView, name='organizations'),
    url(r'^newOrganization.html$',views.newOrganizationView,name='newOrganization'),
    url(r'^submitNewOrganization$',views.submitNewOrganization,name='submitNewOrganization'),
    url(r'^submitNewPotentialOrg$',views.submitNewPotentialOrg,name='submitNewPotentialOrg'),

    url(r'^(?P<organization_id>\d+)/orgTypeView',views.orgTypeView,name='orgTypeView'),
    url(r'^(?P<organization_id>\d+)/submitOrgType', views.submitOrgType, name='submitOrgType'),

    url(r'^(?P<organization_id>\d+)/setMonetaryDistView', views.setMonetaryDistView, name='setMonetaryDistView'),
    url(r'^(?P<organization_id>\d+)/submitMonetaryDist', views.submitMonetaryDist, name='submitMonetaryDist'),

    url(r'^(?P<organization_id>\d+)/setGovernanceView', views.setGovernanceView, name='setGovernanceView'),
]

org_home/urls.py
from django.conf.urls import url
from . import views

app_name = 'org_home'

urlpatterns = [
    url(r'^(?P<organization_id>\d+)/$', views.IndexView, name='index'),

    url(r'^(?P<organization_id>\d+)/categories$', views.CategoryView, name='categories'),

    # new category
    url(r'^(?P<organization_id>\d+)/newCategory.html$',views.newCategoryView,name='newCategory'),
    url(r'^(?P<organization_id>\d+)/(?P<category_id>\d+)/newCategory.html$',views.newCategoryView,name='newSubCategory'),
    url(r'^(?P<organization_id>\d+)/submitNewCategory$',views.submitNewCategory,name='submitNewCategory'),
    url(r'^(?P<organization_id>\d+)/(?P<category_id>\d+)/submitNewCategory$',views.submitNewCategory,name='submitNewSubCategory'),

    # access to organization
    url(r'^(?P<organization_id>\d+)/joinOrganization$', views.JoinOrganization, name='joinOrganization'),
    url(r'^(?P<organization_id>\d+)/orgMembers$', views.orgMembersView, name='orgMembersView'),
    url(r'^(?P<organization_id>\d+)/pendingOrgMembers$', views.orgPendingMembersView, name='orgPendingMembersView'),
    url(r'^(?P<organization_id>\d+)/(?P<pending_member_id>\d+)/grantOrgAccess$', views.GrantAccessToOrg, name='GrantOrgAccess'),

    url(r'^(?P<organization_id>\d+)/(?P<category_id>\d+)/$', views.IndividualCategoryView, name='individualCategory'),

    # payment system
    url(r'^(?P<organization_id>\d+)/cryptoPayView$', views.cryptoPayView, name='cryptoPayView'),

    # access to category
    url(r'^(?P<organization_id>\d+)/(?P<category_id>\d+)/joinCategory$', views.JoinCategory, name='joinCategory'),
    url(r'^(?P<organization_id>\d+)/(?P<category_id>\d+)/members$', views.membersView, name='membersView'),
    url(r'^(?P<organization_id>\d+)/(?P<category_id>\d+)/moderators', views.modsView, name='modsView'),
    url(r'^makeMod', views.makeMod, name='makeMod'),

    # viewing and accepting pending members of category
    url(r'^(?P<organization_id>\d+)/(?P<category_id>\d+)/pendingMembers$', views.pendingMembersView, name='pendingMembersView'),
    url(r'^(?P<organization_id>\d+)/(?P<category_id>\d+)/(?P<pending_member_id>\d+)/grant_access$', views.GrantAccess, name='GrantAccess'),

    # positions
    url(r'^(?P<organization_id>\d+)/(?P<category_id>\d+)/positions', views.positionsView, name='positionsView'),
    url(r'^(?P<organization_id>\d+)/(?P<category_id>\d+)/newPositionView', views.newPositionView, name='newPositionView'),
    url(r'^(?P<organization_id>\d+)/(?P<category_id>\d+)/submitNewPosition$', views.submitNewPosition,name='submitNewPosition'),
    url(r'^(?P<organization_id>\d+)/(?P<category_id>\d+)/(?P<position_id>\d+)/$', views.individualPosition, name='individualPosition'),

    # request to join position
    url(r'^requestToJoinPos', views.requestToJoinPos, name='requestToJoinPos'),
    url(r'^grantAccessToPosition', views.grantAccessToPosition, name='grantAccessToPosition'),

    # helper
    url(r'^userInCategory',views.userInCategory,name='userInCategory'),
]

user_profiles/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from . import views

app_name = 'user_profiles'


urlpatterns = [
    url(r'^(?P<user>\S+)$', views.ProfileView, name='ProfileView'),
]

home/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User

class Organizations(models.Model):
    organization_name = models.CharField(max_length=100)
    description = models.CharField(max_length=1000, default='')

    organization_type = models.CharField(max_length=100, default='')

    pending_members = models.ManyToManyField(User,related_name='organization_pending_member')
    members = models.ManyToManyField(User,related_name='organization_member')
    moderators = models.ManyToManyField(User,related_name='organization_super_member')

    closed_organization = models.BooleanField(default=False)
    gateKeeper = models.CharField(max_length=30, default='') # either all_members or moderators

    contract_address = models.CharField(max_length=1000, default='')

    is_published = models.BooleanField(default=False)

    def __str__(self):
        return self.organization_name

class MonetaryDistribution(models.Model):
    organization = models.ForeignKey(Organizations, on_delete=models.CASCADE)

    # Profit Partitions
    InvestorsWorkersFounders = models.FloatField(default=80)
    OrgBank = models.FloatField(default=14)
    ServiceFee = models.FloatField(default=6)

    # Investment
    sharesPerDollarInvested = models.FloatField(default=100)

    # Contributing
    sharesPerUpvoteOnForumPost = models.FloatField(default=0)
    sharesPerUpvoteOnContribution = models.FloatField(default=10)
    sharesPerAcceptedPostedIdea = models.FloatField(default=100)
    sharesPerUsedContrib = models.FloatField(default=100)

    # Founder bonus
    numOriginalFounders = models.FloatField(default=10)
    sharesPerFounderBonus = models.FloatField(default=100000)

    # Code contributions
    sharesPerEachUseOfCode = models.FloatField(default=50)
    sharesPerLineAcceptedCode = models.FloatField(default=100)

    # Enable the use of machine learning of learn how valuable contribuitons are and reward based on model
    machineLearningShareDistr = models.BooleanField(default=False)


class PowerStack(models.Model):
    PercentDepartmentMustVote = models.BooleanField(default=False)
    AddingMembers = models.BooleanField(default=False)
    RemovingMembers = models.BooleanField(default=False)
    ElectionSystem = models.BooleanField(default=False)
    VotingSystem = models.BooleanField(default=False)
    AppointingPositions = models.BooleanField(default=False)
    CreatingPositions = models.BooleanField(default=False)
    AcceptingContributions = models.BooleanField(default=False)
    RejectingContributions = models.BooleanField(default=False)
    FinalDecisions = models.BooleanField(default=False)
    ChangingMonetaryDistribution = models.BooleanField(default=False)
    AssigningTasks = models.BooleanField(default=False)

class DepartmentStack(models.Model):
    Finance = models.BooleanField(default=False)
    BusinessStrategyAndDevelopment = models.BooleanField(default=False)
    Accounting = models.BooleanField(default=False)
    Recruiting = models.BooleanField(default=False)
    ResearchAndDevelopment = models.BooleanField(default=False)
    Engineering = models.BooleanField(default=False)
    IT = models.BooleanField(default=False)
    MarketingAndAdvertising = models.BooleanField(default=False)
    Administration = models.BooleanField(default=False)
    Sales = models.BooleanField(default=False)
    Purchasing = models.BooleanField(default=False)
    QualityAssurance = models.BooleanField(default=False)
    Licenses = models.BooleanField(default=False)
    CustomerAssurance = models.BooleanField(default=False)
    ProductionAndInventory = models.BooleanField(default=False)
    SupplyChainManagement = models.BooleanField(default=False)

class SystemOfGovernance(models.Model):
    organization = models.ForeignKey(Organizations, on_delete=models.CASCADE)
    category = models.ForeignKey('org_home.Categories', blank=True, null=True)

    # types of governance:
    #    DirectDemocracy
    #    DepartmentReps
    #    Hierarchical
    typeFoGovernance = models.CharField(max_length=500, default='MixDeptRepsDirectDem')

    # Departments organization has:
    departments = models.ForeignKey(DepartmentStack)

    # Voting System in Departments: two voting types: shareBased, and OneVotePerMember
    votingType = models.CharField(max_length=500, default='shareBased', blank=True, null=True)
    votingLength = models.FloatField(default=172800) # 172800 seconds is 2 days             # amount of time users can vote

    # Election System in Departments:
    doElectionsOccur = models.BooleanField(default=False)
    frequencyOfElections = models.IntegerField(default=0)
    maxNumberReElections = models.IntegerField(default=0)

    # Super Member Criteria
    minNumberMemberDays = models.IntegerField(default=0)
    minNumberShares = models.IntegerField(default=0)
    minNumberAcceptedContribs = models.IntegerField(default=0)
    votedIn = models.BooleanField(default=False)
    acceptedByAuthority = models.BooleanField(default=False)

    # founders
    founders = models.ManyToManyField(User)

    # scenarios
    userRetainSharesAfterBanishment = models.BooleanField(default=True)

home/templates/home/base.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'home/style.css' %}" />

<article>
    <header>
        <div id="AccountControls" style="float:right; padding:20px; padding-top: 15px;">
            {% if user.is_authenticated %}
                <a style="text-decoration:none" href="{% url 'user_profiles:ProfileView' user %}">Profile |</a>
                <a style="text-decoration:none" href="{% url 'account_logout' %}">Sign Out</a>
            {% else %}
                <a style="text-decoration:none" href="{% url 'account_login' %}">Sign In |</a>
                <a style="text-decoration:none" href="{% url 'account_signup' %}">Sign Up</a>
            {% endif %}
        </div>

        <div id="GroupRoots">
            <a style="display:block; font-size:30; text-align:center; color:#1f90e3; float:left; padding-left: 25px; text-decoration:none " href = "{% url 'home:index' %}">Contrib</a><a style="display:block; font-size:30; text-align:center; color:#008200; float:left; padding-left: 0px; text-decoration:none " href = "{% url 'home:index' %}">Pay</a>
        </div>
        {% block headerContent %}
        {% endblock %}
    </header>
        {% block content %}
        {% endblock %}
</article>

home/templates/home/index.html
{% extends "home/base.html"  %}
{% load static %}

{% block content %}

    <main>
        {% if member_organizations_list %}
        <h3> Your organizations:</h3>
            <ul style="list-style: none;">
            {% for organization in member_organizations_list %}
                <li> <a href="{% url 'org_home:index' organization.id %}"> {{ organization }} </a> </li>
            {% endfor %}
            </ul>
        {% endif %}
    </main>


    <div id="tasks">
        <a style="padding-right:5px" href="{% url 'home:organizations' %}"> Explore Organizations and Projects </a><br/>
        <a href = "{% url 'home:newOrganization' %}">Create a New Organization / Project</a>
    </div>

{% endblock %}

home/templates/home/newOrganization.html
{% extends "home/base.html"  %}
{% load static %}

{% block headerContent %}
    <a style="font-size: 29px; text-decoration:none; padding-right:5px; margin-left: 28%;" href="#">Create new Organization</a>
{% endblock %}   

{% block content %}

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<main>
    <form action="{% url 'home:submitNewOrganization' %}" method="post">
    {% csrf_token %}
        <div style="margin-top: 20px;" id="forms">
            <label>Name: </label>
            <input type="text" name="new_organization" id="new_organization"/><br/><br/>

            <label>Description: </label>
            <input type="text" name="new_organization_desc" id="new_organization_desc"/><br/><br/>

            <label>Payment System: </label>
            <input type="radio" name="paymentSystem" id="bankAccount"/><label>Bank Account</label>
            <input type="radio" name="paymentSystem" id="cryptoPayment"/><label>Crypto Currency</label><br/><br/>

        </div>
        <input type="submit" value="Create"/>
    </form>
</main>

{% endblock %}





<!--{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}-->


<!--<form action="{% url 'home:submitNewOrganization' %}" method="post">-->
<!--{% csrf_token %}-->
    <!--<h1>Create new Branch</h1>-->
    <!--<div id="forms">-->
        <!--<label>Name: </label>-->
        <!--<input type="text" name="new_organization" id="new_organization"/><br/><br/>-->
        <!--<label>Need permission to join? </label>-->
        <!--<input type="checkbox" onclick="permission()" name="closed_organization" id="closed_organization"/><br/><br/>-->
        <!--<label id="1" style="display:none">Who can grant permission? </label><br/>-->
        <!--<label id="2" style="display:none">All Members</label>-->
        <!--<input type="radio" name="access" id="members_access" value="all_members" style="display:none"/><br/>-->
        <!--<label id="3" style="display:none">Moderator</label>-->
        <!--<input type="radio" name="access" id="moderators_access" value="moderators" style="display:none"/><br/><br/>-->
    <!--</div>-->
    <!--<input type="submit" value="Submit"/>-->
<!--</form>-->

<!--<script>-->
<!--function permission(){-->

    <!--if (document.getElementById('closed_organization').checked){-->
        <!--document.getElementById("members_access").style.display = '';-->
        <!--document.getElementById("moderators_access").style.display = '';-->
        <!--document.getElementById("1").style.display = '';-->
        <!--document.getElementById("2").style.display = '';-->
        <!--document.getElementById("3").style.display = '';-->
        <!--}-->
    <!--else{-->
        <!--document.getElementById("members_access").style.display = 'none';-->
        <!--document.getElementById("moderators_access").style.display = 'none';-->
        <!--document.getElementById("1").style.display = 'none';-->
        <!--document.getElementById("2").style.display = 'none';-->
        <!--document.getElementById("3").style.display = 'none';-->
        <!--}-->
    <!--}-->
<!--</script>-->

home/templates/home/orgType.html
{% extends "home/base.html"  %}
{% load static %}

{% block content %}

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<main>
    <form action="{% url 'home:submitOrgType' organization.id %}" method="post">
    {% csrf_token %}
        <div id="forms">
            <h1 style="margin-left: 30%">Type of Organization: </h1>

            <ul class="orgTypeButtons">
                <li>
                    <input type="radio" name="org_type" id="non_profit" value="non_profit" />
                    <label for="non_profit">Non Profit</label>
                </li>
                <li>
                    <input type="radio" name="org_type" id="for_profit" value="for_profit" />
                    <label for="for_profit">For Profit</label>
                </li>
                <li>
                    <input type="radio" name="org_type" id="regular_org" value="regular_org" />
                    <label for="regular_org">Basic Organization</label>
                </li>
            </ul>


        </div>
        <br/><br/><br/><br/><br/>

        <input style="float:right" type="submit" value="Next"/>
    </form>
</main>

{% endblock %}

home/templates/home/organizations.html
{% extends "home/base.html"  %}
{% load static %}


{% block headerContent %}
    <a style="font-size: 29px; text-decoration:none; padding-right:5px; margin-left: 33%;" href="#">Organizations</a>
{% endblock %}   

{% block content %}
<aside>
    <div id="myOrgsNav">
        {% if member_organizations_list %}
            <p style="display:block; text-align:center; font-size: 20; text-decoration:none;">Your Organizations</p>
            {% for organization in member_organizations_list %}
                <a class="myOrgItem" href="{% url 'org_home:index' organization.id %}"> {{ organization }} </a>
            {% endfor %}
        {% else %}
            <p style="display:block; text-align:center; font-size: 20; text-decoration:none;">Member of no organizations</p>
            <p style="display:block; text-align:center; font-size: 20; text-decoration:none;">... join or create one</p>
        {% endif %}
    </div>
</aside>

<div style="grid-column: 2; width:90%; " id="feed">

    <div style="background-color: #4d4e4e; width:195px; height: 25px; text-align: center; padding-top: 5px; border-radius: 7px; margin-left: 15px; margin-top: 10px;">
        <a style="color:white;" href = "{% url 'home:newOrganization' %}">Create a New Organization</a>
    </div>

    {% if organizations_list %}
        {% for organization in organizations_list %}
            <div style="padding: 20 20 20 20; background-color: white; width:20%; height:100px; margin-left: 15px; margin-top: 15px; border-style: solid; border-color: #d6d6d8;border-width: thin; border-radius: 4px; display:inline-grid; text-align: center;">
                <a style="font-weight: bold;" href="{% url 'org_home:index' organization.id %}"> {{ organization }} </a>
                <p style="margin-top: 0;">{{ organization.description }}</p>
                {% if organization.members.all.count == 1 %}
                    <p>{{ organization.members.all.count }} member</p>
                {% else %}
                    <p>{{ organization.members.all.count }} members</p>
                {% endif %}
            </div>
        {% endfor %}
    {% else %}
        <p>No organizations are available.</p>
    {% endif %}

</div>

{% endblock %}

home/templates/home/profile_login_out.html
<div style="float: right; padding: 20px;">
    {% if user.is_authenticated %}
    <a style="text-decoration:none" href="{% url 'user_profiles:ProfileView' user %}">Profile |</a>
    <a style="text-decoration:none" href="{% url 'account_logout' %}">Sign Out</a>
    {% else %}
    <a style="text-decoration:none" href="{% url 'account_login' %}">Sign In |</a>
    <a style="text-decoration:none" href="{% url 'account_signup' %}">Sign Up</a>
    {% endif %}
</div>

home/templates/home/setMonetaryDistribution.html
{% extends "home/base.html"  %}
{% load static %}

{% block content %}
<script src="http://code.interactjs.io/v1.3.4/interact.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<main>
    <form action="{% url 'home:submitMonetaryDist' organization.id %}" method="post">
    {% csrf_token %}
        <div id="forms">
            <h1 style="margin-left: 30%">Set Monetary Distribution: </h1>
            <br/>
            <h3>Profit Split: </h3>
            <div class="profitPartitions">
                <div style="background-color:#29e" class="resize-drag">
                    Investors, Workers, Founders:
                    <br/><br/>
                    <input value="80" type="number" style="width:40px; margin-left:45px; margin-right: 5px;" name="profitPartitions" id="iwfPercent"/>%
                </div>
                <div style="background-color:#1b78bb" class="resize-drag">
                    Organization Bank:
                    <br/><br/><br/>
                    <input value="14" type="number" style="width:40px; margin-left:45px; margin-right: 5px;" name="profitPartitions" id="orgBankPercent"/>%
                </div>
                <div style="background-color:#166298" class="resize-drag">
                    Service:
                    <br/><br/>
                    <p style="margin-left: 40%">6%</p>
                </div>
            </div>

            <br/>

            <h3>Share Rewards:</h3>
            <div style="border-style: dashed; border-color: #8f8f8f; color:grey; border-width: thin; padding:10px;text-align: center;vertical-align: middle;">
                Total number of shares in Organization starts at 0
            </div>
            <ul style="margin: 20px;list-style: none;">
                <li class="shareDist"><label>Shares per $1 invested: </label><input value="100" type="number" style="width:60px; margin-left:5px; margin-right: 5px;" name="sharesPerDollar" id="sharesPerDollar"/></li>
            <!--     <li class="shareDist"><label>Shares Per Upvote on Forum Post: </label><input value="0" type="number" style="width:60px; margin-left:5px; margin-right: 5px;" name="sharesPerForumUpvote" id="sharesPerForumUpvote"/></li> -->
                <li class="shareDist"><label>Shares Per Upvote on Contribution: </label><input value="10" type="number" style="width:60px; margin-left:5px; margin-right: 5px;" name="sharesPerContribUpvote" id="sharesPerContribUpvote"/></li>
     <!--            <li class="shareDist"><label>Shares per Accepted Posted Idea: </label><input value="100" type="number" style="width:60px; margin-left:5px; margin-right: 5px;" name="sharesPerAcceptedIdea" id="sharesPerAcceptedIdea"/></li> -->
                <li class="shareDist"><label>Base number of shares per used contribution: </label><input value="100" type="number" style="width:60px; margin-left:5px; margin-right: 5px;" name="baseNumberSharesUsedContrib" id="baseNumberSharesUsedContrib"/></li>
                <li class="shareDist"><label>Shares for being one of the first </label><input value="10" type="number" style="width:40px; margin-left:5px; margin-right: 5px;" name="initialFounderNum" id="initialFounderNum"/><label> people to join and contribute: </label><input value="100000" type="number" style="width:60px; margin-left:5px; margin-right: 5px;" name="initialFounderBonus" id="initialFounderBonus"/></li>
                <li><br/></li>
      <!--           <li class="shareDist"><label>Shares for each use of code written (in other peices of code or other): </label><input value="50" type="number" style="width:60px; margin-left:5px; margin-right: 5px;" name="codeUseReward" id="codeUseReward"/></li>
                <li class="shareDist"><label>Shares per line of approved code: </label><input value="100" type="number" style="width:60px; margin-left:5px; margin-right: 5px;" name="SharesPerLine" id="SharesPerLine"/></li> -->
               <!--  <li><br/></li>
                <li class="shareDist"><label>Use machine learning to set value to contributions? </label><br/><label>Yes</label><input type="radio" name="machine_learning_distr" id="machine_learning_distr_yes" value="true"/><label>No</label><input type="radio" name="machine_learning_distr" id="machine_learning_distr_no" value="false" checked/></li> -->
            </ul>

        </div>
        <br/><br/><br/><br/><br/>

        <input style="float:right" type="submit" value="Next"/>
    </form>



<!-- The resizable tiles... do this later instead of current -->


<!--<main>-->
    <!--<form action="{% url 'home:submitMonetaryDist' organization.id %}" method="post">-->
    <!--{% csrf_token %}-->
        <!--<div id="forms">-->
            <!--<h1 style="margin-left: 30%">Set Monetary Distribution: </h1>-->
            <!--<br/>-->
            <!--<h3>Profit Split: </h3>-->
            <!--<div class="profitPartitions">-->
                <!--<div style="background-color:#29e" class="resize-drag">-->
                    <!--Investors, Workers, Founders: 50%-->
                <!--</div>-->
                <!--<div style="background-color:#1b78bb" class="resize-drag">-->
                    <!--Org Bank: 50%-->
                <!--</div>-->
            <!--</div>-->

        <!--</div>-->
        <!--<br/><br/><br/><br/><br/>-->

        <!--<input style="float:right" type="submit" value="Next"/>-->
    <!--</form>-->

<!--<script>-->
    <!--interact('.resize-drag')-->
      <!--.draggable({-->
        <!--onmove: window.dragMoveListener,-->
        <!--restrict: {-->
          <!--restriction: 'parent',-->
          <!--elementRect: { top: 0, left: 0, bottom: 1, right: 1 }-->
        <!--},-->
      <!--})-->
      <!--.resizable({-->
        <!--// resize from all edges and corners-->
        <!--edges: { left: true, right: true, bottom: true, top: true },-->

        <!--// keep the edges inside the parent-->
        <!--restrictEdges: {-->
          <!--outer: 'parent',-->
          <!--endOnly: true,-->
        <!--},-->

        <!--// minimum size-->
        <!--restrictSize: {-->
          <!--min: { width: 0, height: 125 },-->
          <!--max: { width: $('.profitPartitions').width()/2, height: 125 }-->
        <!--},-->

        <!--inertia: true,-->
      <!--})-->
      <!--.on('resizemove', function (event) {-->
        <!--var target = event.target,-->
            <!--x = (parseFloat(target.getAttribute('data-x')) || 0),-->
            <!--y = (parseFloat(target.getAttribute('data-y')) || 0);-->

        <!--// update the element's style-->
        <!--target.style.width  = event.rect.width + 'px';-->
        <!--target.style.height = event.rect.height + 'px';-->

        <!--// translate when resizing from top or left edges-->
        <!--x += event.deltaRect.left;-->
        <!--y += event.deltaRect.top;-->

        <!--target.style.webkitTransform = target.style.transform =-->
            <!--'translate(' + x + 'px,' + y + 'px)';-->

        <!--target.setAttribute('data-x', x);-->
        <!--target.setAttribute('data-y', y);-->
        <!--// target.textContent = Math.round(event.rect.width) + '\u00D7' + Math.round(event.rect.height);-->
        <!--target.textContent = "Investors, Workers, Founders: " + Math.round(event.rect.width / $('.profitPartitions').width() * 100) + "%";-->
      <!--});-->
<!--</script>-->

</main>

{% endblock %}