consensusEditing/urls.py
from django.conf.urls import url
from . import views

app_name = 'consensusEditing'

urlpatterns = [
    # view main text-doc
    url(r'^(?P<textdoc_id>\d+)/(?P<organization_id>\d+)/textDoc', views.textDoc,name='textDoc'),

    # edit main text-doc
    url(r'^(?P<textdoc_id>\d+)/(?P<organization_id>\d+)/editTextDoc', views.editTextDoc,name='editTextDoc'),

    # view the proposals
    url(r'^(?P<main_text_doc_id>\d+)/(?P<organization_id>\d+)/proposals', views.viewProposals, name='viewProposals'),

    # view specific proposal
    url(r'^(?P<text_proposal_id>\d+)/(?P<organization_id>\d+)/viewTextProposal', views.viewTextProposal,name='viewTextProposal'),

    # vote
    url(r'^proposalVote',views.proposalVote,name='proposalVote'),
]

gameCoop/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^accounts/', include('allauth.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^vote/', include('vote.urls')),
    url(r'^org_work/', include('org_work.urls')),
    url(r'^org_struct/', include('org_struct.urls')),
    url(r'^org_home/', include('org_home.urls')),
    url(r'^activity_feed/', include('activity_feed.urls')),
    url(r'^user_profiles/', include('user_profiles.urls')),
    url(r'^discuss/', include('discuss.urls')),
    url(r'^home/', include('home.urls')),
    url(r'^home/', include('home.urls')),
    url(r'^consensusEditing/', include('consensusEditing.urls')),
]

home/urls.py
from django.conf.urls import url
from . import views

app_name = 'home'

urlpatterns = [
    # url(r'^$', views.IndexView, name='index'),
    url(r'^$', views.OrganizationView, name='index'),

    url(r'^organizations', views.OrganizationView, name='organizations'),
    url(r'^newOrganization.html$',views.newOrganizationView,name='newOrganization'),
    url(r'^submitNewOrganization$',views.submitNewOrganization,name='submitNewOrganization'),
    url(r'^submitNewPotentialOrg$',views.submitNewPotentialOrg,name='submitNewPotentialOrg'),

    url(r'^(?P<organization_id>\d+)/orgTypeView',views.orgTypeView,name='orgTypeView'),
    url(r'^(?P<organization_id>\d+)/submitOrgType', views.submitOrgType, name='submitOrgType'),

    url(r'^(?P<organization_id>\d+)/setMonetaryDistView', views.setMonetaryDistView, name='setMonetaryDistView'),
    url(r'^(?P<organization_id>\d+)/submitMonetaryDist', views.submitMonetaryDist, name='submitMonetaryDist'),

    url(r'^(?P<organization_id>\d+)/setGovernanceView', views.setGovernanceView, name='setGovernanceView'),
]

consensusEditing/models.py
from django.db import models
from org_home.models import Categories
from home.models import Organizations
from org_work.models import Projects
from django.contrib.auth.models import User

class TextDoc(models.Model):
    # Title and description of the document
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)

    # Who created the document. Empty if automatically created
    poster = models.OneToOneField(User,blank=True, null=True)

    # Organization, Category, or Project
    location_type = models.CharField(max_length=100)
    organization = models.ForeignKey(Organizations, on_delete=models.CASCADE, blank=True, null=True)
    category = models.ForeignKey(Categories, on_delete=models.CASCADE, blank=True, null=True)
    project = models.ForeignKey(Projects, blank=True, null=True)

    # If the document is the main document or a proposal (proposal is like a branch)
    isMain = models.BooleanField()
    # relation between this document and its main document
    mainDoc = models.ForeignKey("self", blank=True, null=True)

    # path to the document in the filesystem
    pathToFile = models.CharField(max_length=500)
    # pathToFile = models.URLField()

class vote(models.Model):
    textDoc = models.ForeignKey(TextDoc, on_delete=models.CASCADE)
    votes = models.IntegerField(default=0)
    voters = models.ManyToManyField(User)

consensusEditing/views.py
from __future__ import unicode_literals
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse
from django.urls import reverse
from django.views import generic
from django.contrib.auth.decorators import login_required
import os
import itertools

from django.shortcuts import render
from home.models import Organizations
from org_home.models import Categories
from django.db.models import F
from consensusEditing.models import TextDoc,vote
from django.views.decorators.csrf import csrf_exempt
from activity_feed.views import submitActivity

@login_required
def textDoc(request, textdoc_id, organization_id=None):

    # get the text-doc from the id
    text_doc = get_object_or_404(TextDoc,id=textdoc_id)
    path = text_doc.pathToFile
    title = text_doc.title

    # get the text file
    with open(path, 'r') as f:
        text = f.read()

    organization = text_doc.organization

    return render(request, 'consensusEditing/text_doc.html',{'organization':organization,
                                                             'categories_list': Categories.objects.filter(organization=organization, ),
                                                             'text':text,
                                                             'textdoc_id':textdoc_id,
                                                             'title':title,
                                                             })

def editTextDoc(request, textdoc_id, organization_id=None):
    text = request.POST['content']

    text_doc = get_object_or_404(TextDoc, id=textdoc_id)
    path = text_doc.pathToFile
    title = text_doc.title

    organization = text_doc.organization

    # get the main document
    if(text_doc.isMain == True):
        mainDoc = text_doc
    else:
        mainDoc = text_doc.mainDoc

    # delete any old proposals a user has for the same main document
    if len(TextDoc.objects.filter(mainDoc=mainDoc,poster=request.user)) > 0:
        TextDoc.objects.filter(mainDoc=mainDoc, poster=request.user).delete()
        #deleteTextDoc()

    # create the new proposal
    proposal_text_doc = TextDoc.objects.create(title=title,
                                      description=text_doc.description,
                                      location_type=text_doc.location_type,
                                      isMain=False,
                                      mainDoc=mainDoc,
                                      organization=organization,
                                      poster=request.user,
                                      )
    proposal_text_doc.save()
    proposal_path = "/Users/andrei/gameCoop2/storage/organizations/" + organization_id + "/proposals/" + \
                    str(mainDoc.pk) + "/" + str(proposal_text_doc.pk) + ".txt"
    proposal_text_doc.pathToFile = proposal_path
    proposal_text_doc.save()

    # create a vote object for that proposal
    voteObj = vote.objects.create(textDoc=proposal_text_doc)
    voteObj.save()

    # submit an activity
    url = reverse('consensusEditing:viewTextProposal', args=(proposal_text_doc.id,organization.id))
    submitActivity(str(request.user) + " proposed an edit to " + str(text_doc.title), url, organization_id)


    # in the proposals folder create a folder with the id of the main text doc and put the proposal doc in there
    if(text_doc.mainDoc == None):
        command = "cd storage " \
                  "\n cd organizations" \
                  "\n cd " + organization_id + \
                  "\n cd proposals" \
                  "\n mkdir " + str(text_doc.pk) + \
                  "\n cd " + str(text_doc.pk) + \
                  '\n echo "' \
                  + text + '" >> ' + str(proposal_text_doc.pk) + '.txt '

    else:
        command = "cd storage " \
                  "\n cd organizations" \
                  "\n cd " + organization_id + \
                  "\n cd proposals" \
                  "\n mkdir " + str(text_doc.mainDoc.pk) + \
                  "\n cd " + str(text_doc.mainDoc.pk) + \
                  '\n echo "' \
                  + text + '" >> ' + str(proposal_text_doc.pk) + '.txt '
    os.system(command)
    return render(request, 'consensusEditing/text_proposal.html', {'organization': organization,
                                                               'categories_list': Categories.objects.filter(organization=organization, ),
                                                              'text': text,
                                                              'highLighted_text':text,
                                                              'textdoc_id':proposal_text_doc.id,
                                                              'main_id': mainDoc.pk,
                                                              'title':title,
                                                              })

    # else:
    #     warning = "Updating the proposal will reset the voting and discussion. Do you wish to continue?"
    #     return render(request, 'consensusEditing/text_doc.html', {'organization': organization,
    #                                                               'text': text,
    #                                                               'textdoc_id': textdoc_id,
    #                                                               'title': title,
    #                                                               'error': warning
    #                                                               })

def viewProposals(request,main_text_doc_id,organization_id=None):
    main_text_doc = get_object_or_404(TextDoc, id=main_text_doc_id)
    organization = main_text_doc.organization
    proposalsList = TextDoc.objects.filter(mainDoc=main_text_doc,)
    return render(request, 'consensusEditing/proposals.html', {'organization': organization,
                                                               'categories_list': Categories.objects.filter(organization=organization, ),
                                                               'proposals_list': proposalsList
    })


def viewTextProposal(request, text_proposal_id, organization_id=None):
    organization = None

    # get the text-doc from the id
    text_doc = get_object_or_404(TextDoc,id=text_proposal_id)
    path = text_doc.pathToFile
    title = text_doc.title

    organization = text_doc.organization

    # get the text file of the proposal
    with open(path, 'r') as f:
        text = f.read()

    # get the text of of the main doc
    main_doc = text_doc.mainDoc
    main_doc_path = main_doc.pathToFile
    with open(main_doc_path,'r') as f:
        main_text = f.read()

    # get the lines with the difference between the main and proposal
    linesWithDiff = getModifications(main_text,text)

    # highlight text on the modified lines
    highLighted_text = highlightText(linesWithDiff,text)

    return render(request, 'consensusEditing/text_proposal.html',{'organization':organization,
                                                             'categories_list': Categories.objects.filter(organization=organization, ),
                                                             'text':text,
                                                             'highLighted_text':highLighted_text,
                                                             'textdoc_id':text_proposal_id,
                                                             'title':title,
                                                             })

# returns a list of the line numbers that are different
def getModifications(original, modified):
    originalLines = original.split('\n')
    modifiedLines = modified.split('\n')

    linesWithDiff = []

    for i,(originalLine, modifiedLine) in enumerate(itertools.zip_longest(originalLines,modifiedLines)):
        if(originalLine!=modifiedLine):
            linesWithDiff.append(i)

    return linesWithDiff

# returns the text with highlighted html on the line numbers given
def highlightText(linesWithDiff,text):
    newText = ''
    lines = text.split('\n')
    for i,line in enumerate(lines):
        if(i in linesWithDiff):
            newLine = '<mark>' + line + '</mark>\n'
            newText += newLine
        else:
            newText += line
        newText += '\n'
    return newText

@csrf_exempt
def proposalVote(request):
    text_proposal_id = int(request.POST.get('text_proposal_id'))

    # get the text-doc from the id
    proposal = get_object_or_404(TextDoc, id=text_proposal_id)
    proposal_path = proposal.pathToFile

    # get the text file of the proposals
    with open(proposal_path, 'r') as f:
        proposal_text = f.read()

    # get the text of of the main doc
    main_doc = proposal.mainDoc
    main_doc_path = main_doc.pathToFile

    voteObj = vote.objects.filter(textDoc=proposal)[0]

    votes = voteObj.votes
    voters = voteObj.voters.all()
    voteObj.save()

    threshhold = getPassingThreshhold(text_proposal_id)

    if request.user not in voters:
        voteObj.voters.add(request.user)
        voteObj.votes = F('votes') + 1
        voteObj.save()

    # if yes votes passes the threshold then overwrite main with the proposal
    if votes >= threshhold:
        with open(main_doc_path,'w') as f:
            f.write(proposal_text)

        # commit the main git with the new edit
        commitTextDocGit(main_doc.pk)

        # delete the proposal
        deleteTextDoc(proposal.pk)

    return HttpResponse(status=204)

def getPassingThreshhold(text_proposal_id):
    proposal = get_object_or_404(TextDoc, id=text_proposal_id)
    threshhold = 0;

    # maybe put the threshold in the model of the organization
    if proposal.location_type == 'Organization':
        organization = proposal.organization
        numUsers = organization.members.count()
        threshhold = int(numUsers * .51)

    return threshhold


def deleteTextDoc(text_doc_id):

consensusEditing/templates/consensusEditing/proposals.html
{% extends "org_home/base.html"  %}
{% load static %}

{% block content2 %}
{% with organization=organization categories_list=categories_list projects_list=projects_list %}
<link rel="stylesheet" type="text/css" href="{% static 'org_home/style.css' %}" />

<main>
    <h1>list of proposals:</h1>

    <ul style="list-style: none;">
        {% for proposal in proposals_list %}
            <li> <a href="{% url 'consensusEditing:viewTextProposal' proposal.id organization.id %}"> {{ proposal.poster }}'s change </a> </li>
        {% endfor %}
    </ul>
</main>

{% endwith %}
{% endblock %}

consensusEditing/templates/consensusEditing/text_doc.html
{% extends "org_home/base.html"  %}
{% load static %}

{% block content2 %}
{% with organization=organization categories_list=categories_list projects_list=projects_list %}
<link rel="stylesheet" type="text/css" href="{% static 'org_home/style.css' %}" />

<main>
    <h2 style="width:100%; margin-top:20px;">{{ title }}</h2>
    {% if main_id != null %}
        <a href="{% url 'consensusEditing:viewProposals' main_id organization.id %}">Proposed Edits</a>
    {% else %}
        <a href="{% url 'consensusEditing:viewProposals' textdoc_id organization.id %}">Proposed Edits</a>
    {% endif %}
    <form style="margin-top: 15px;" action="{% url 'consensusEditing:editTextDoc' textdoc_id organization.id %}" method="post">
        {% csrf_token %}
        <div id="editAndSubmit">

            <input type="submit" value="Submit"/>
            <input type="button"  id="editButton" value="Edit" onclick="enableEdit()"/>

        </div>

        <textarea readonly hidden style="font-size:12; padding:5px; max-width:100%; width:100%; height:600px; outline:none; color:slategrey; margin-top: 27px; border-color:lightgrey" id="contentEditor" name="content">{{ text }}</textarea><br/>
        <div id="viewText" style="border:1px solid lightgrey; padding:5px; width:98%; margin-top: 10px;">
            <span id="viewTextSpan" style="white-space: pre-line; width:100%; height:600px; color:slategrey; margin-top: 10px;" >{{ text|safe }}</span><br/>
        </div>
    </form>
</main>

<script>
    function enableEdit(){
        document.getElementById("contentEditor").removeAttribute('readonly','false');
        document.getElementById("contentEditor").style.color = 'black';
        document.getElementById("contentEditor").style.borderColor = 'grey';

        document.getElementById("editButton").remove();
        document.getElementById("editAndSubmit").innerHTML += "<input id='doneButton' type='button' value='Done' onclick='endEdit()'/>"

        document.getElementById("viewText").hidden = true;
        document.getElementById("contentEditor").hidden = false;
    }

    function endEdit(){
        document.getElementById("contentEditor").setAttribute('readonly','true');
        document.getElementById("contentEditor").style.color = 'slategrey';
        document.getElementById("contentEditor").style.borderColor = 'lightgrey';

        document.getElementById("doneButton").remove();
        document.getElementById("editAndSubmit").innerHTML += "<input id='editButton' type='button' value='Edit' onclick='enableEdit()'/>"

        document.getElementById("viewText").hidden = false;
        document.getElementById("contentEditor").hidden = true;
        document.getElementById("viewTextSpan").innerText = document.getElementById("contentEditor").value;
    }

</script>

{% endwith %}
{% endblock %}

consensusEditing/templates/consensusEditing/text_proposal.html
{% extends "org_home/base.html"  %}
{% load static %}

{% block content2 %}
{% with organization=organization categories_list=categories_list projects_list=projects_list %}
<link rel="stylesheet" type="text/css" href="{% static 'org_home/style.css' %}" />

<main>
    <div style="width:100%; margin-top:20px;">
        <h2>{{ title }} Proposal</h2>
        <button onclick="vote( {{ textdoc_id }} )">yay</button>
        <button>nay</button> Need to still add to "voters" for nay
        <p> Maybe have a discussion thing here on the side</p>
    </div>

    <form style="margin-top: 15px;" action="{% url 'consensusEditing:editTextDoc' textdoc_id organization.id %}" method="post">
        {% csrf_token %}
        <div id="editAndSubmit">

            <input type="submit" value="Submit"/>
            <input type="button"  id="editButton" value="Edit" onclick="enableEdit()"/>

        </div>

        <textarea readonly hidden style="font-size:12; padding:5px; max-width:100%; width:100%; height:600px; outline:none; color:slategrey; margin-top: 27px; border-color:lightgrey" id="contentEditor" name="content">{{ text }}</textarea><br/>
        <div id="viewText" style="border:1px solid lightgrey; padding:5px; width:98%; margin-top: 10px;">
            <span id="viewTextSpan" style="white-space: pre-line; width:100%; height:600px; color:slategrey; margin-top: 10px;" >{{ text|safe }}</span><br/>
        </div>
    </form>
</main>

<script>
    function enableEdit(){
        document.getElementById("contentEditor").removeAttribute('readonly','false');
        document.getElementById("contentEditor").style.color = 'black';
        document.getElementById("contentEditor").style.borderColor = 'grey';

        document.getElementById("editButton").remove();
        document.getElementById("editAndSubmit").innerHTML += "<input id='doneButton' type='button' value='Done' onclick='endEdit()'/>"

        document.getElementById("viewText").hidden = true;
        document.getElementById("contentEditor").hidden = false;
    }

    function endEdit(){
        document.getElementById("contentEditor").setAttribute('readonly','true');
        document.getElementById("contentEditor").style.color = 'slategrey';
        document.getElementById("contentEditor").style.borderColor = 'lightgrey';

        document.getElementById("doneButton").remove();
        document.getElementById("editAndSubmit").innerHTML += "<input id='editButton' type='button' value='Edit' onclick='enableEdit()'/>"

        document.getElementById("viewText").hidden = false;
        document.getElementById("contentEditor").hidden = true;
        document.getElementById("viewTextSpan").innerText = document.getElementById("contentEditor").value;
    }

    function vote(textdoc_id)
        {
            $.ajax(
            {
                'type': "POST",
                'dataType': 'html',
                'url': "{% url 'consensusEditing:proposalVote' %}",
                'data': {text_proposal_id:textdoc_id},
                'success': function () {
                }
            });
            return HttpResponse(status=204)
        }

</script>

{% endwith %}
{% endblock %}