gameCoop/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^accounts/', include('allauth.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^vote/', include('vote.urls')),
    url(r'^org_work/', include('org_work.urls')),
    url(r'^org_struct/', include('org_struct.urls')),
    url(r'^org_home/', include('org_home.urls')),
    url(r'^activity_feed/', include('activity_feed.urls')),
    url(r'^user_profiles/', include('user_profiles.urls')),
    url(r'^discuss/', include('discuss.urls')),
    url(r'^home/', include('home.urls')),
    url(r'^home/', include('home.urls')),
    url(r'^consensusEditing/', include('consensusEditing.urls')),
]

home/urls.py
from django.conf.urls import url
from . import views

app_name = 'home'

urlpatterns = [
    # url(r'^$', views.IndexView, name='index'),
    url(r'^$', views.OrganizationView, name='index'),

    url(r'^organizations', views.OrganizationView, name='organizations'),
    url(r'^newOrganization.html$',views.newOrganizationView,name='newOrganization'),
    url(r'^submitNewOrganization$',views.submitNewOrganization,name='submitNewOrganization'),
    url(r'^submitNewPotentialOrg$',views.submitNewPotentialOrg,name='submitNewPotentialOrg'),

    url(r'^(?P<organization_id>\d+)/orgTypeView',views.orgTypeView,name='orgTypeView'),
    url(r'^(?P<organization_id>\d+)/submitOrgType', views.submitOrgType, name='submitOrgType'),

    url(r'^(?P<organization_id>\d+)/setMonetaryDistView', views.setMonetaryDistView, name='setMonetaryDistView'),
    url(r'^(?P<organization_id>\d+)/submitMonetaryDist', views.submitMonetaryDist, name='submitMonetaryDist'),

    url(r'^(?P<organization_id>\d+)/setGovernanceView', views.setGovernanceView, name='setGovernanceView'),
]

org_home/urls.py
from django.conf.urls import url
from . import views

app_name = 'org_home'

urlpatterns = [
    url(r'^(?P<organization_id>\d+)/$', views.IndexView, name='index'),

    url(r'^(?P<organization_id>\d+)/categories$', views.CategoryView, name='categories'),

    # new category
    url(r'^(?P<organization_id>\d+)/newCategory.html$',views.newCategoryView,name='newCategory'),
    url(r'^(?P<organization_id>\d+)/(?P<category_id>\d+)/newCategory.html$',views.newCategoryView,name='newSubCategory'),
    url(r'^(?P<organization_id>\d+)/submitNewCategory$',views.submitNewCategory,name='submitNewCategory'),
    url(r'^(?P<organization_id>\d+)/(?P<category_id>\d+)/submitNewCategory$',views.submitNewCategory,name='submitNewSubCategory'),

    # access to organization
    url(r'^(?P<organization_id>\d+)/joinOrganization$', views.JoinOrganization, name='joinOrganization'),
    url(r'^(?P<organization_id>\d+)/orgMembers$', views.orgMembersView, name='orgMembersView'),
    url(r'^(?P<organization_id>\d+)/pendingOrgMembers$', views.orgPendingMembersView, name='orgPendingMembersView'),
    url(r'^(?P<organization_id>\d+)/(?P<pending_member_id>\d+)/grantOrgAccess$', views.GrantAccessToOrg, name='GrantOrgAccess'),

    url(r'^(?P<organization_id>\d+)/(?P<category_id>\d+)/$', views.IndividualCategoryView, name='individualCategory'),

    # payment system
    url(r'^(?P<organization_id>\d+)/cryptoPayView$', views.cryptoPayView, name='cryptoPayView'),

    # access to category
    url(r'^(?P<organization_id>\d+)/(?P<category_id>\d+)/joinCategory$', views.JoinCategory, name='joinCategory'),
    url(r'^(?P<organization_id>\d+)/(?P<category_id>\d+)/members$', views.membersView, name='membersView'),
    url(r'^(?P<organization_id>\d+)/(?P<category_id>\d+)/moderators', views.modsView, name='modsView'),
    url(r'^makeMod', views.makeMod, name='makeMod'),

    # viewing and accepting pending members of category
    url(r'^(?P<organization_id>\d+)/(?P<category_id>\d+)/pendingMembers$', views.pendingMembersView, name='pendingMembersView'),
    url(r'^(?P<organization_id>\d+)/(?P<category_id>\d+)/(?P<pending_member_id>\d+)/grant_access$', views.GrantAccess, name='GrantAccess'),

    # positions
    url(r'^(?P<organization_id>\d+)/(?P<category_id>\d+)/positions', views.positionsView, name='positionsView'),
    url(r'^(?P<organization_id>\d+)/(?P<category_id>\d+)/newPositionView', views.newPositionView, name='newPositionView'),
    url(r'^(?P<organization_id>\d+)/(?P<category_id>\d+)/submitNewPosition$', views.submitNewPosition,name='submitNewPosition'),
    url(r'^(?P<organization_id>\d+)/(?P<category_id>\d+)/(?P<position_id>\d+)/$', views.individualPosition, name='individualPosition'),

    # request to join position
    url(r'^requestToJoinPos', views.requestToJoinPos, name='requestToJoinPos'),
    url(r'^grantAccessToPosition', views.grantAccessToPosition, name='grantAccessToPosition'),

    # helper
    url(r'^userInCategory',views.userInCategory,name='userInCategory'),
]

org_struct/urls.py
from django.conf.urls import url
from . import views

app_name = 'org_struct'

urlpatterns = [
    url(r'^(?P<organization_id>\d+)/$', views.IndexView, name='index'),

    # url(r'^(?P<organization_id>\d+)/monetary_distribution$', views.MoneyDistributionView,name='monetary_distribution'),
    # url(r'^(?P<organization_id>\d+)/community_editing', views.community_editing,name='community_editing')
]

org_work/urls.py
from django.conf.urls import url
from . import views
from . import GitIntegration

app_name = 'org_work'

urlpatterns = [
    url(r'^(?P<organization_id>\d+)/(?P<category_id>\d+)/categoryWork', views.IndexView, name='index'),
    url(r'^(?P<organization_id>\d+)/projects/(?P<project_id>\d+)/$', views.IndividualProjectView, name='individualProjectNoCat'),
    url(r'^(?P<organization_id>\d+)/projects/(?P<project_id>\d+)/(?P<category_id>\d+)/$', views.IndividualProjectView, name='individualProject'),
    url(r'^(?P<organization_id>\d+)/(?P<category_id>\d+)/$', views.ProjectView, name='projects'),

    # create new project
    url(r'^(?P<organization_id>\d+)/newProject.html$',views.newProjectView,name='newProject'),
    url(r'^(?P<organization_id>\d+)/(?P<category_id>\d+)/newProject.html$',views.newProjectView,name='newSubProject'),
    url(r'^(?P<organization_id>\d+)/submitNewProject',views.submitNewProject,name='submitNewProject'),
    url(r'^(?P<organization_id>\d+)/(?P<original_cat>\d+)/submitNewProject$',views.submitNewProject,name='submitNewSubProject'),

    # submit work
    url(r'^(?P<organization_id>\d+)/(?P<category_id>\d+)/SubmitWorkView', views.SubmitWorkView, name='SubmitWorkView'),
    url(r'^(?P<organization_id>\d+)/(?P<category_id>\d+)/submitWork', views.submitWork, name='submitWork'),

    # view non accepted contribution
    url(r'^(?P<organization_id>\d+)/(?P<category_id>\d+)/pendingWork$', views.pendingWork, name='pendingWork'),

    # ajax
    url(r'(?P<organization_id>\d+)/(?P<project_id>\d+)/CreateGitRepo',GitIntegration.CreateGitRepo,name='CreateGitRepo'),
    url(r'(?P<organization_id>\d+)/(?P<project_id>\d+)/ConnectGitHub',GitIntegration.ConnectGitHub,name='ConnectGitHub'),
    url(r'(?P<organization_id>\d+)/(?P<organization_name>[\w\s\S]+)/(?P<project_id>\d+)/(?P<project_name>[\w\s\S]+)/getGitURL',GitIntegration.getGitURL,name='getGitURL'),
    url(r'^ProjectsInCommon', views.ProjectsInCommon, name='ProjectsInCommon'),
    url(r'^contribVote',views.voteForContrib,name='voteForContrib'),
    url(r'^acceptRejectWork',views.acceptRejectWork,name='acceptRejectWork'),
]

org_home/forms.py
from django import forms
from .models import Categories
from home.models import Organizations
from django.shortcuts import get_object_or_404

class ParentCategories(forms.Form):
    parent_branch = forms.ChoiceField(choices = [])

org_home/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse
from django.views import generic, View
from django.shortcuts import render
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt

from .models import Categories
from .models import Positions
from org_work.models import Projects
from org_work.models import WorkSubmissions
from home.models import Organizations
from .forms import ParentCategories


# ------------------------------------------------------------------------------------------------ #
# organization
#

# org_home page of a coop
@login_required
def IndexView(request,organization_id):
    organization = get_object_or_404(Organizations,pk=organization_id)
    userPercentageInOrg = round(getUserPercentageInOrg(organization, request.user) * 100,3)
    return render(request, 'org_home/index.html',
                  { 'organization': organization,
                    'member_categories_list': Categories.objects.filter(members__id=request.user.id,organization=organization),
                    'categories_list':Categories.objects.filter(organization=organization),
                    'projects_list': Projects.objects.filter(organization=organization),
                    'userPercentageInOrg': userPercentageInOrg,
                  })

# list of all members in an organization
@login_required
def orgMembersView(request,organization_id):
    organization = get_object_or_404(Organizations,id=organization_id)
    return render(request,'org_home/org_members.html',{'organization':organization,'categories_list':Categories.objects.filter(organization=organization)})

# list of pending members in an organization
@login_required
def orgPendingMembersView(request,organization_id):
    # this html is also called in GrantAccess
    organization = get_object_or_404(Organizations,id=organization_id)
    return render(request,'org_home/org_pending_members.html',{'organization':organization,'categories_list':Categories.objects.filter(organization=organization)})

# join the organization
@login_required
def JoinOrganization(request,organization_id):
    '''
    if open organization, add user to members list of org
    if closed org, add user to pending_members list of org
    '''
    organization = get_object_or_404(Organizations,id=organization_id)
    # if org is open
    if organization.closed_organization == False:
        organization.members.add(request.user)
    else:
        organization.pending_members.add(request.user)
    return HttpResponseRedirect(reverse('org_home:index', args=(organization.id,)))

# grant access to someone to become a member of an organization
@login_required
def GrantAccessToOrg(request,organization_id,pending_member_id):
    organization = get_object_or_404(Organizations,id=organization_id)
    pending_member = User.objects.get(pk=pending_member_id)

    # if any member can add pending members to category
    if organization.gateKeeper == 'all_members':
        if request.user in organization.members.all():
            organization.members.add(pending_member)
            organization.pending_members.remove(pending_member)
    # if only moderator can add pending members to category
    elif organization.gateKeeper == 'moderators':
        if request.user in organization.moderators.all():
            organization.members.add(pending_member)
            organization.pending_members.remove(pending_member)
        else:
            return render(request,'org_home/org_pending_members.html',{'organization':organization,'error_message':'Must be a moderator to add user to ' +  organization })
    return HttpResponseRedirect(reverse('org_home:orgPendingMembersView', args=(organization.id,)))


# ------------------------------------------------------------------------------------------------ #
# category... aka Department or Branch (within Organization)
#


# list of all the categories/root/branch in a coop DELETE THIS I THINK
@login_required
def CategoryView(request,organization_id):
    organization = get_object_or_404(Organizations,id=organization_id)
    return render(request,'org_home/categories.html',{'organization':organization,'categories_list':Categories.objects.filter(organization=organization)})

# org_home page of specific category/root/branch in a coop
@login_required
def IndividualCategoryView(request,organization_id,category_id):
    organization = get_object_or_404(Organizations,id=organization_id)
    category = get_object_or_404(Categories,pk=category_id)
    real_cat = category
    subCategories = Categories.objects.filter(parent=category)
    ancestorCategories = getCategoryAncestors(category_id)
    projects_list = Projects.objects.filter(organization=organization,category=category)

    if category.needAcceptedContribs:
        submissionsList = WorkSubmissions.objects.filter(
                organization=organization,
                category=category,
                accepted=True,
            ).order_by('-pub_date')[:10]
    else:
        submissionsList = WorkSubmissions.objects.filter(
                organization=organization,
                category=category,
            ).order_by('-pub_date')[:10]
    
    no_subs_message=""
    if len(submissionsList) == 0:
        no_subs_message = "No submissions here yet"

    contribsUserLiked = getContribsUserLiked(request.user, organization, category)

    num_pending = WorkSubmissions.objects.filter(
                organization=organization,
                category=category,
                accepted=False,
                ).count()

    return render(request,'org_home/individualCategory.html',{'organization':organization,
                                                            'category': category,
                                                            'real_cat' : real_cat,
                                                            'subCategories':subCategories,
                                                            'categories_list':Categories.objects.filter(organization=organization,),
                                                            'ancestor_categories_list':ancestorCategories,
                                                            'projects_list':projects_list,
                                                            'submissionsList': submissionsList,
                                                            'no_subs_message': no_subs_message,
                                                            'contribsUserLiked': contribsUserLiked,
                                                            'num_pending': num_pending,
                                                            })

# ------ payment system -----

# list of all members in an organization
@login_required
def cryptoPayView(request,organization_id):
    organization = get_object_or_404(Organizations,id=organization_id)
    contract_address = organization.contract_address
    userPercentageInOrg = round(getUserPercentageInOrg(organization, request.user) * 100,3)
    return render(request,'org_home/cryptoPay.html',{
        'organization':organization,
        'categories_list':Categories.objects.filter(organization=organization),
        'contract_address':contract_address,
        'userPercentageInOrg': userPercentageInOrg})



# --- helper functions -----

def getCategoryAncestors(category_id):
    currentCategory = get_object_or_404(Categories,pk=category_id)
    ancestors = []
    while currentCategory.parent != None:
        ancestors.insert(0,currentCategory.parent)
        currentCategory = currentCategory.parent
    return ancestors

@csrf_exempt
def userInCategory(request):
    category_id = int(request.POST.get('category_id'))
    category = get_object_or_404(Categories, pk=category_id)
    if request.user in category.members.all():
        return HttpResponse(1)
    return HttpResponse(0)

def getContribsUserLiked(user, organization, category):
    allContribs = WorkSubmissions.objects.filter(organization=organization,category=category)
    contribs = []
    for contrib in allContribs:
        if user in contrib.user_up_votes.all():
            contribs.append(contrib)
    return contribs

# def getUserPercentageInCategory(organization, category, user):
#     # total number of points in category (post * likes per post)
#     numCategoryPoints = 0

#     # total number of points user has in category
#     numUserPointsInCat = 0

#     # get all the submissions in the category
#     categorySubmissions = WorkSubmissions.objects.filter(organization=organization, category=category)
#     for submission in categorySubmissions:
#         numCategoryPoints += (1 + submission.user_up_votes.count())



#     userSubmissions = WorkSubmissions.objects.filter(organization=organization, category=category, poster=user)
#     for submission in userSubmissions:
#         numUserPointsInCat += (1 + submission.user_up_votes.count())

#     if(numCategoryPoints > 0):
#         percentUsersSubsInCat = numUserPointsInCat / numCategoryPoints
#         return percentUsersSubsInCat

#     return 0

def getUserPercentageInOrg(organization, user):
    # total number of points in org (post * likes per post)
    numOrgPoints = 0

    # total number of points user has in category
    numUserPointsInOrg = 0

    # get all the submissions in the category
    orgSubmissions = WorkSubmissions.objects.filter(organization=organization, accepted=True)
    for submission in orgSubmissions:
        numOrgPoints += (1 + submission.user_up_votes.count())

    userSubmissions = WorkSubmissions.objects.filter(organization=organization, poster=user, accepted=True)

    for submission in userSubmissions:
        numUserPointsInOrg += (1 + submission.user_up_votes.count())

org_home/templates/org_home/index.html
{% extends "org_home/base.html" %}
{% load static %}

{% block content2 %}
{% with organization=organization categories_list=categories_list projects_list=projects_list %}
<link rel="stylesheet" type="text/css" href="{% static 'org_home/style.css' %}" />

    {% if user in organization.members.all %}
        <main>
            <br/>
            {% if organization.closed_organization %}
                <div class="categoryMenuItems" style="height: 75px">
                    <a style="text-decoration:none;" href="{% url 'org_home:orgPendingMembersView' organization.id %}">Pending Members</a>
                </div><br/>
            {% endif %}
            <div class="categoryMenuItems" style="height: 75px">
                <a style="text-decoration:none;" href="{% url 'org_home:orgMembersView' organization.id %}">Members</a>
            </div>

            <div class="categoryMenuItems" style="height: 75px">
                <a href="{% url 'org_struct:index' organization.id %}">Constitution</a>
            </div>

            <div class="categoryMenuItems" style="height: 75px">
                <a style="text-decoration:none;" href="{% url 'org_home:cryptoPayView' organization.id %}">Payments</a><br/>
            </div>

            {% if user.is_authenticated %}
            {% if member_categories_list %}
            <div style="border-width: thin; border-style: solid; border-color: #d6d6d8; padding-right:10px; padding-bottom: 10px; margin-top: 10px; margin-bottom: 10px; text-align: center;">
                <h3> My departments:</h3>
                    {% for category in member_categories_list %}
                        <a class="myCatItem" style="text-decoration:none;" href="{% url 'org_home:individualCategory' organization.id category.id %}"> {{ category }} </a>
                    {% endfor %}
            </div>
            {% endif %}

            <div style="border-width: thin; border-style: solid; border-color: #d6d6d8; padding-left:20px; margin-top: 20px; margin-bottom: 10px; text-align: center;">
                <h3> Your contributions percentage: {{ userPercentageInOrg }}%</h3>
            </div>
            
            {% endif %}

        </main>
    {% elif user in organization.pending_members.all %}
        <main>
            <p style="font-style: italic; margin-bottom: 0; margin-left: 10px;">Pending membership</p>
            <div style="margin-left: 5px; margin-top: 25px;" class="categoryMenuItems">
                <a style="text-decoration:none;" href="">Info</a><br/>
            </div>
            <div style="margin-left: 5px; margin-top: 25px;" class="categoryMenuItems">
                <a style="text-decoration:none;" href="">Pay</a><br/>
            </div>
        </main>
    {% else %}
        <main>
            <div style="margin-left: 5px; margin-top: 25px;" class="categoryMenuItems">
                <a style="text-decoration:none;" href="{% url 'org_home:joinOrganization' organization.id %}">Join</a>
            </div>
            <div class="categoryMenuItems">
                <a style="text-decoration:none;" href="">Info</a>
            </div>
            <div class="categoryMenuItems">
                <a style="text-decoration:none;" href="">Pay</a><br/>
            </div>
        </main>
    {% endif %}


    <!--<div id="feed">-->
    <!--<h2>Activity Feed</h2>-->
        <!--<p>Check the "in review" thing in gits. Then post them here</p>-->
        <!--<a href="">Jared changed the logo</a> <a href="">Yay</a> <a href="">Nay</a> <a href="">Discuss</a>-->
    <!--</div>-->

    <!-- Activity Feed -->




{% endwith %}
{% endblock %}

org_home/templates/org_home/individualCategory.html
{% extends "org_home/base.html" %}
{% load static %}

{% block content2 %}
{% with organization=organization category=category categories_list=categories_list projects_list=projects_list %}
<link rel="stylesheet" type="text/css" href="{% static 'org_home/style.css' %}" />
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <main>
        {% if user in category.members.all %}
            <br/>
            <div class="categoryMenuItems">
                <a style="text-decoration:none;" href="">Info</a>
            </div>
            <!--{% if user in category.moderators.all %}-->
                <!--<div class="categoryMenuItems">-->
                    <!--<a style="text-decoration:none;" href="">Moderator Access</a>-->
                <!--</div>-->
            <!--{% endif %}-->
            {% if category.closed_category %}
                <div class="categoryMenuItems">
                    <a style="text-decoration:none;" href="{% url 'org_home:pendingMembersView' organization.id category.id %}">Pending Members</a><br/>
                </div>
            {% endif %}
            <!--<div class="categoryMenuItems">-->
                <!--<a style="text-decoration:none;" href="">Files</a>-->
            <!--</div>-->
        {% endif %}

        {% if user in category.pending_members.all %}
            <p style="font-style: italic; margin-bottom: 0; margin-left: 10px;">Pending membership</p>
        {% endif %}

        {% if user not in category.members.all %}
            <br/>
            <div class="categoryMenuItems">
                <a style="text-decoration:none;" href="{% url 'org_home:joinCategory' organization.id category.id %}">Join</a>
            </div>
            <div class="categoryMenuItems">
                <a style="text-decoration:none;" href="">Info</a><br/>
            </div>
        {% endif %}

        <div class="categoryMenuItems">
            <a style="text-decoration:none;" href="{% url 'org_home:membersView' organization.id category.id %}">Members</a>
        </div>
        <div class="categoryMenuItems">
            <a style="text-decoration:none;" href="{% url 'org_home:modsView' organization.id category.id %}">Moderators</a>
        </div>
    </main>

    {% if user in category.members.all %}
        <div id="feed">
            <h3 style='margin-top: 30; margin-left: 10px; padding-top: 0; margin-bottom: 10px;'>Contributions </h3>
            {% if user in category.moderators.all %}
                {% if category.needAcceptedContribs %}
                    <div style="background-color: #4d4e4e; width:195px; height: 25px; text-align: center; padding-top: 5px; border-radius: 7px; margin-left: 10px; margin-top: 10px;">
                        <a style="text-decoration:none; color:white;" href="{% url 'org_work:pendingWork' organization.id category.id %}">Pending Contributions ({{ num_pending }})</a>
                    </div>
                {% endif %}
            {% endif %}
            <!-- <div style="width:100%; border-style:solid; border-color: #e8e8e8; border-width: 1px; padding-top: 0px; "></div>  -->
            <div style="background-color: #4d4e4e; width:195px; height: 25px; text-align: center; padding-top: 5px; border-radius: 7px; margin-left: 10px; margin-top: 10px;">
                <a style="color:white;" href="{% url 'org_work:SubmitWorkView' organization.id category.id %}">Add New Contribution</a><br/>
            </div>
            {% for submission in submissionsList %}
                <div style="padding: 20 20 20 20; background-color: white; width:100%; margin-top: 15px; margin-right: 0px; border-style: solid;border-color: #d6d6d8;border-width: thin;border-radius: 4px;" class="contribItem">
                    <label style='font-size: 12px; color:grey;'>Submitted by {{ submission.poster }}</label><br/>
                    <a style='font-size: 20px;font-weight:bold;' href={{ submission.linkToSubmission }}>{{ submission.title }}</a><br/><br/>
                    <label>{{ submission.description }}</label><br/><br/>

                    <div class="vote-buttons">
                        {% if contribsUserLiked is None or submission not in contribsUserLiked %}
                            <img style="cursor: pointer;" class="vote-up" id="{{submission.id}}_submissionUp" src="{% static 'images/thumbs-up.png'%}" width="16" height="16"/><label> Upvote</label>
                        {% else %}
                            <img style="cursor: pointer;" class="vote-up selected" id="{{submission.id}}_submissionUp" src="{% static 'images/thumbs-up-selected.png'%}" width="16" height="16"/><label style="color:#393939; font-weight:bold;"> Upvote</label>
                        {% endif %}
                        <label id="{{submission.id}}_score">{{ submission.user_up_votes.count }}</label>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% endif %}

    <script>
        $(document).ready(function()
        {
            $('div.vote-buttons img.vote-up').click(function() {
               var id = this.id;
               var submissionID = id.split("_")[0];
               var contentId = submissionID + '_score';

               var clicked = $('#' + id);
               if (clicked.hasClass('selected'))
               {
                    var vote_action = 'recall-vote';
                    $.post("{% url 'org_work:voteForContrib' %}", {id:submissionID, action:vote_action,
                        csrfmiddlewaretoken:'{{ csrf_token }}'}, function(response)
                    {
                        if(response.includes("error")) {
                            window.alert(response);
                        } else{
                            var responseNum = Number(response);
                            clicked.removeAttr('src');
                            clicked.attr('src', '{% static 'images/thumbs-up.png'%}')
                            clicked.removeClass('selected');
                            document.getElementById(contentId).innerHTML = responseNum;
                            document.getElementById(contentId).style = color;
                        }
                    });
               }
               else
               {
                    var vote_action = 'vote';
                    $.post("{% url 'org_work:voteForContrib' %}", {id:submissionID, action:vote_action,
                        csrfmiddlewaretoken:'{{ csrf_token }}'}, function(response)
                    {
                        if(response.includes("error")) {
                            window.alert(response);
                        } else{
                            var responseNum = Number(response);
                            clicked.removeAttr('src');
                            clicked.attr('src', '{% static 'images/thumbs-up-selected.png'%}');
                            clicked.addClass('selected');
                            document.getElementById(contentId).innerHTML = responseNum;
                        }
                    });
               }
            });
        });
    </script>

{% endwith %}
{% endblock %}

org_home/templates/org_home/individualPosition.html
{% extends "org_home/base.html" %}
{% load static %}


{% block content2 %}
{% with organization=organization category=category categories_list=categories_list %}
<link rel="stylesheet" type="text/css" href="{% static 'org_home/style.css' %}" />
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <main>
        <h1> {{ position.position_name }} </h1>
        <p>Description: {{ position.description }}</p>
        <div style="border-style: solid; border-width:thin; border-color: #d6d6d8; padding:10px; margin-top: 10px; margin-bottom: 10px;">
            <label>Position holders:</label>
            <ul id="membersInPosition">
            {% for user in users.all %}
                <li>{{ user }}</li>
            {% endfor %}
            </ul>
        </div>

        </br>

        {% if position.position_requesters.all %}
            {% if user in position.position_holders.all %}
                <div style="border-style: solid; border-width:thin; border-color: #d6d6d8; padding:10px; margin-top: 10px; margin-bottom: 10px;">
                    <label>Position requesters:</label>
                    <ul>
                        {% for pending_member in position.position_requesters.all %}
                            <li id="{{pending_member.id}}_request">{{ pending_member }} <a style="cursor:pointer;color:#2200CC;" onclick="grantAccess('{{ pending_member.pk }}', '{{ pending_member }}')">Grant Access</a></li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        {% endif %}


        {% if user not in position.position_holders.all %}
            {% if user not in position.position_requesters.all %}
                <a id="request" style="cursor:pointer;color:#2200CC;" onclick="joinRequest()">Request to Join</a>
                <label id="requestSent" hidden>Position Requested</label><br/>
            {% else %}
                <label>Position Requested</label><br/>
            {% endif %}
        {% endif %}

        <script>
           function joinRequest()
           {
                $.ajax(
                {
                    'type': "POST",
                    'dataType': 'html',
                    'url': "{% url 'org_home:requestToJoinPos' %}",
                    'data': {position_id: {{ position.id }} },
                    'success': function(data) {
                        $('#request').remove();
                        $('#requestSent').show();
                    }
                });
           }

           function grantAccess(pendingMemberId, pendingMemberName)
           {
                $.ajax(
                {
                    'type': "POST",
                    'dataType': 'html',
                    'url': "{% url 'org_home:grantAccessToPosition' %}",
                    'data': {position_id: {{ position.id}}, user_id: parseInt(pendingMemberId) },
                    'success': function(data) {
                        var id = "#" + pendingMemberId + "_request";
                        $(id).remove();
                        $("#membersInPosition").append($("<li>" + pendingMemberName +  "</li>"));
                    }
                });
           }
        </script>

    </main>

{% endwith %}
{% endblock %}