gameCoop/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^accounts/', include('allauth.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^vote/', include('vote.urls')),
    url(r'^org_work/', include('org_work.urls')),
    url(r'^org_struct/', include('org_struct.urls')),
    url(r'^org_home/', include('org_home.urls')),
    url(r'^activity_feed/', include('activity_feed.urls')),
    url(r'^user_profiles/', include('user_profiles.urls')),
    url(r'^discuss/', include('discuss.urls')),
    url(r'^home/', include('home.urls')),
    url(r'^home/', include('home.urls')),
    url(r'^consensusEditing/', include('consensusEditing.urls')),
]

home/urls.py
from django.conf.urls import url
from . import views

app_name = 'home'

urlpatterns = [
    # url(r'^$', views.IndexView, name='index'),
    url(r'^$', views.OrganizationView, name='index'),

    url(r'^organizations', views.OrganizationView, name='organizations'),
    url(r'^newOrganization.html$',views.newOrganizationView,name='newOrganization'),
    url(r'^submitNewOrganization$',views.submitNewOrganization,name='submitNewOrganization'),
    url(r'^submitNewPotentialOrg$',views.submitNewPotentialOrg,name='submitNewPotentialOrg'),

    url(r'^(?P<organization_id>\d+)/orgTypeView',views.orgTypeView,name='orgTypeView'),
    url(r'^(?P<organization_id>\d+)/submitOrgType', views.submitOrgType, name='submitOrgType'),

    url(r'^(?P<organization_id>\d+)/setMonetaryDistView', views.setMonetaryDistView, name='setMonetaryDistView'),
    url(r'^(?P<organization_id>\d+)/submitMonetaryDist', views.submitMonetaryDist, name='submitMonetaryDist'),

    url(r'^(?P<organization_id>\d+)/setGovernanceView', views.setGovernanceView, name='setGovernanceView'),
]

org_home/urls.py
from django.conf.urls import url
from . import views

app_name = 'org_home'

urlpatterns = [
    url(r'^(?P<organization_id>\d+)/$', views.IndexView, name='index'),

    url(r'^(?P<organization_id>\d+)/categories$', views.CategoryView, name='categories'),

    # new category
    url(r'^(?P<organization_id>\d+)/newCategory.html$',views.newCategoryView,name='newCategory'),
    url(r'^(?P<organization_id>\d+)/(?P<category_id>\d+)/newCategory.html$',views.newCategoryView,name='newSubCategory'),
    url(r'^(?P<organization_id>\d+)/submitNewCategory$',views.submitNewCategory,name='submitNewCategory'),
    url(r'^(?P<organization_id>\d+)/(?P<category_id>\d+)/submitNewCategory$',views.submitNewCategory,name='submitNewSubCategory'),

    # access to organization
    url(r'^(?P<organization_id>\d+)/joinOrganization$', views.JoinOrganization, name='joinOrganization'),
    url(r'^(?P<organization_id>\d+)/orgMembers$', views.orgMembersView, name='orgMembersView'),
    url(r'^(?P<organization_id>\d+)/pendingOrgMembers$', views.orgPendingMembersView, name='orgPendingMembersView'),
    url(r'^(?P<organization_id>\d+)/(?P<pending_member_id>\d+)/grantOrgAccess$', views.GrantAccessToOrg, name='GrantOrgAccess'),

    url(r'^(?P<organization_id>\d+)/(?P<category_id>\d+)/$', views.IndividualCategoryView, name='individualCategory'),

    # payment system
    url(r'^(?P<organization_id>\d+)/cryptoPayView$', views.cryptoPayView, name='cryptoPayView'),

    # access to category
    url(r'^(?P<organization_id>\d+)/(?P<category_id>\d+)/joinCategory$', views.JoinCategory, name='joinCategory'),
    url(r'^(?P<organization_id>\d+)/(?P<category_id>\d+)/members$', views.membersView, name='membersView'),
    url(r'^(?P<organization_id>\d+)/(?P<category_id>\d+)/moderators', views.modsView, name='modsView'),
    url(r'^makeMod', views.makeMod, name='makeMod'),

    # viewing and accepting pending members of category
    url(r'^(?P<organization_id>\d+)/(?P<category_id>\d+)/pendingMembers$', views.pendingMembersView, name='pendingMembersView'),
    url(r'^(?P<organization_id>\d+)/(?P<category_id>\d+)/(?P<pending_member_id>\d+)/grant_access$', views.GrantAccess, name='GrantAccess'),

    # positions
    url(r'^(?P<organization_id>\d+)/(?P<category_id>\d+)/positions', views.positionsView, name='positionsView'),
    url(r'^(?P<organization_id>\d+)/(?P<category_id>\d+)/newPositionView', views.newPositionView, name='newPositionView'),
    url(r'^(?P<organization_id>\d+)/(?P<category_id>\d+)/submitNewPosition$', views.submitNewPosition,name='submitNewPosition'),
    url(r'^(?P<organization_id>\d+)/(?P<category_id>\d+)/(?P<position_id>\d+)/$', views.individualPosition, name='individualPosition'),

    # request to join position
    url(r'^requestToJoinPos', views.requestToJoinPos, name='requestToJoinPos'),
    url(r'^grantAccessToPosition', views.grantAccessToPosition, name='grantAccessToPosition'),

    # helper
    url(r'^userInCategory',views.userInCategory,name='userInCategory'),
]

org_work/urls.py
from django.conf.urls import url
from . import views
from . import GitIntegration

app_name = 'org_work'

urlpatterns = [
    url(r'^(?P<organization_id>\d+)/(?P<category_id>\d+)/categoryWork', views.IndexView, name='index'),
    url(r'^(?P<organization_id>\d+)/projects/(?P<project_id>\d+)/$', views.IndividualProjectView, name='individualProjectNoCat'),
    url(r'^(?P<organization_id>\d+)/projects/(?P<project_id>\d+)/(?P<category_id>\d+)/$', views.IndividualProjectView, name='individualProject'),
    url(r'^(?P<organization_id>\d+)/(?P<category_id>\d+)/$', views.ProjectView, name='projects'),

    # create new project
    url(r'^(?P<organization_id>\d+)/newProject.html$',views.newProjectView,name='newProject'),
    url(r'^(?P<organization_id>\d+)/(?P<category_id>\d+)/newProject.html$',views.newProjectView,name='newSubProject'),
    url(r'^(?P<organization_id>\d+)/submitNewProject',views.submitNewProject,name='submitNewProject'),
    url(r'^(?P<organization_id>\d+)/(?P<original_cat>\d+)/submitNewProject$',views.submitNewProject,name='submitNewSubProject'),

    # submit work
    url(r'^(?P<organization_id>\d+)/(?P<category_id>\d+)/SubmitWorkView', views.SubmitWorkView, name='SubmitWorkView'),
    url(r'^(?P<organization_id>\d+)/(?P<category_id>\d+)/submitWork', views.submitWork, name='submitWork'),

    # view non accepted contribution
    url(r'^(?P<organization_id>\d+)/(?P<category_id>\d+)/pendingWork$', views.pendingWork, name='pendingWork'),

    # ajax
    url(r'(?P<organization_id>\d+)/(?P<project_id>\d+)/CreateGitRepo',GitIntegration.CreateGitRepo,name='CreateGitRepo'),
    url(r'(?P<organization_id>\d+)/(?P<project_id>\d+)/ConnectGitHub',GitIntegration.ConnectGitHub,name='ConnectGitHub'),
    url(r'(?P<organization_id>\d+)/(?P<organization_name>[\w\s\S]+)/(?P<project_id>\d+)/(?P<project_name>[\w\s\S]+)/getGitURL',GitIntegration.getGitURL,name='getGitURL'),
    url(r'^ProjectsInCommon', views.ProjectsInCommon, name='ProjectsInCommon'),
    url(r'^contribVote',views.voteForContrib,name='voteForContrib'),
    url(r'^acceptRejectWork',views.acceptRejectWork,name='acceptRejectWork'),
]

org_work/forms.py
from django import forms

class NewProjectForm(forms.Form):
    project_name = forms.CharField(max_length=30, label='Project Name')

org_work/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.core import serializers
from django.utils import timezone
import json

from org_home.models import Categories
from home.models import Organizations
from .models import Projects
from .models import WorkSubmissions
from org_home.views import getCategoryAncestors

def getProjectAncestors(project_id):
    currentProject = get_object_or_404(Projects,pk=project_id)
    ancestors = []
    while currentProject.parent != None:
        ancestors.insert(0,currentProject.parent)
        currentProject = currentProject.parent
    return ancestors

@login_required
def IndexView(request,organization_id,category_id):
    organization = get_object_or_404(Organizations,pk=organization_id)
    category = get_object_or_404(Categories,pk=category_id)
    ancestorCategories = getCategoryAncestors(category_id)
    projects_list = Projects.objects.filter(organization=organization)


    # ancestorProjects = getProjectAncestors()
    return render(request, 'org_work/index.html',{'organization': organization,'category':category,
                                                  'categories_list':Categories.objects.filter(organization=organization),
                                                  'ancestor_categories_list': ancestorCategories,
                                                  'projects_list':projects_list
                                                  })

def ProjectView(request,organization_id,category_id):
    organization = get_object_or_404(Organizations,pk=organization_id)
    category = get_object_or_404(Categories,pk=category_id)
    return render(request,'org_work/projects.html',{'organization': organization,'category':category,
                                                    'categories_list':Categories.objects.filter(organization=organization)})

def IndividualProjectView(request,organization_id, project_id, category_id=None):
    organization = get_object_or_404(Organizations,pk=organization_id)
    project = get_object_or_404(Projects, pk=project_id)
    if category_id != None:
        category = get_object_or_404(Categories,pk=category_id)
        ancestorCategories = getCategoryAncestors(category_id)
        projects_list = Projects.objects.filter(organization=organization, category=category)
        return render(request,'org_work/individualProject.html',{'organization': organization,'category':category,
                                                        'categories_list':Categories.objects.filter(organization=organization),
                                                        'project':project,
                                                        'ancestor_categories_list': ancestorCategories,
                                                        'projects_list': projects_list
                                                        })
    projects_list = Projects.objects.filter(organization=organization)
    return render(request, 'org_work/individualProject.html', {'organization': organization,
                                                               'categories_list': Categories.objects.filter(organization=organization),
                                                               'project': project,
                                                               'projects_list': projects_list
                                                               })

def newProjectView(request,organization_id,category_id=None,parent_id=None):
    # one of the organizations the project belongs to (just need one bc of naviagtion and already on the org page)
    organization = get_object_or_404(Organizations,id=organization_id)
    ancestorCategories = getCategoryAncestors(category_id)

    # one of the categories the project belongs to.
    category = None
    if category_id != None:
        category = get_object_or_404(Categories,pk=category_id)

    parent = None
    if parent_id != None:
        parent = get_object_or_404(Projects,pk=parent_id)

    return render(request, 'org_work/newProject.html',{'organization':organization,'category':category,
                                                       'categories_list': Categories.objects.filter(organization=organization),
                                                        'ancestor_categories_list':ancestorCategories})

@csrf_exempt
def ProjectsInCommon(request):
    selectedIds = json.loads(request.POST['selectedIds'])
    selectedTreePositions = json.loads(request.POST['selectedTreePositions'])
    maxPosition = int(request.POST.get('maxTreePositions'))
    currentPosition = maxPosition

    commonProjects = set()
    # set of categories that have projects in common
    commonProjectCategories = set()

    # iterate twice so that updates
    k=2
    while k > 0:
        for i,(id,pos) in enumerate(zip(selectedIds,selectedTreePositions)):
            category = get_object_or_404(Categories, pk=selectedIds[i])
            # populate the commonProjects with all projects of category
            if len(commonProjects) == 0 or childInSet(category,commonProjectCategories) or parentInSet(category,commonProjectCategories):
                for proj in category.relatedCategory.all():
                    commonProjects.add(proj)
                    commonProjectCategories.add(category)
            else:
                for proj in commonProjects:
                    if proj not in category.relatedCategory.all():
                        commonProjects.discard(proj)
                        commonProjectCategories.discard(category)
        k-=1

        currentPosition -= 1
    data = serializers.serialize('json', commonProjects)
    return HttpResponse(json.dumps(data), content_type='application/json')

def childInSet(category,set):
    if len(category.category_parent.all()) == 0:
        return category in set
    elif category in set:
        return True
    else:
        for child in category.category_parent.all():
            if childInSet(child,set):
                return True
    return False

def parentInSet(category,set):
    if category.parent == None:
        return category in set
    elif category.parent in set:
        return True
    else:
        return parentInSet(category.parent,set)

# submit a new project
@login_required
def submitNewProject(request, organization_id, original_cat=None):
    organization = get_object_or_404(Organizations,id=organization_id)
    if request.method == "POST":
        if 'new_project' in request.POST and request.POST['new_project'] != '':

            # set project name
            projectName = request.POST['new_project']
            formatedProjectName = ' '.join(word[0].upper() + word[1:] for word in projectName.split())
            # returns error if the category name already exists
            if Projects.objects.filter(organization=organization,project_name=formatedProjectName).exists():
                return render(request, 'org_work/newProject.html', {'organization':organization,'error_message': formatedProjectName + " already exists.",})

            # set categories
            categoriesIds = None
            if 'categoryCheckbox' in request.POST and len(request.POST.getlist('categoryCheckbox'))>0:
                categoriesIds = request.POST.getlist('categoryCheckbox')


            # set parent project
            parent = None
            if 'parent' in request.POST and request.POST['parent'] != "-1":
                parent = get_object_or_404(Projects,pk=int(request.POST['parent']))
                print(parent)

            # create the category
            if True: #add some conditions here based on the conditions of the category they're in
                project = Projects.objects.create(organization=organization,
                                                     parent=parent,
                                                     project_name=formatedProjectName,
                                                    )
                # maybe add a members list

                # add the categories
                for cat_id in categoriesIds:
                    cat = get_object_or_404(Categories,id=cat_id)
                    project.category.add(cat)

                if original_cat == None:
                    original_cat = categoriesIds[0]

                return HttpResponseRedirect(reverse('org_home:individualCategory', args=(organization.id,original_cat)))
            else:
                return render(request, 'org_work/newProject.html', {
                'organization':organization,
                'category': original_cat,
                'error_message': "You do not have permission to make new " + parent.category_name + " branch",
            })
        else:
            return render(request, 'org_work/newProject.html', {
                'organization':organization,
                'category': original_cat,
                'error_message': "Please enter at least one category.",
            })


# submit new work 

def SubmitWorkView(request,organization_id, category_id):
    organization = get_object_or_404(Organizations,pk=organization_id)
    category = get_object_or_404(Categories, pk=category_id)

    return render(request, 'org_work/submitWork.html', {'organization': organization,
                                                               'categories_list': Categories.objects.filter(organization=organization),
                                                               'category': category,
                                                               })


def submitWork(request, organization_id, category_id):
    organization = get_object_or_404(Organizations,pk=organization_id)

org_work/templates/org_work/base.html
{% extends "org_home/base.html" %}
{% load static %}

{% block content2 %}
{% with organization=organization categories_list=categories_list %}

    {% block content3 %}
    {% endblock %}

{% endwith %}
{% endblock %}

org_work/templates/org_work/individualProject.html
{% extends "org_home/base.html" %}
{% load static %}

{% load i18n %}
{% load account socialaccount %}

{% block content2 %}
{% with organization=organization category=category categories_list=categories_list projects_list=projects_list %}
<link rel="stylesheet" type="text/css" href="{% static 'org_home/style.css' %}" />
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <main>
        <h3 style="text-align:center">{{ project.project_name }}</h3>
        <a href="{% url 'org_work:SubmitWorkView' organization.id project.id %}">Submit work</a>
    </main>

    <!--<main>-->
        <!--<h3 style="text-align:center">{{ project.project_name }}</h3>-->
        <!--<a target="_blank" href="https://docs.google.com/spreadsheets/d/1zgGOkRZArM1KEnqPWUmfW-rmYk6J3nKTJ28o1SXKGf0/edit?usp=sharing">Tasks</a>-->
        <!--<p>-->
            <!--The thing is that service needs to keep track of what people do so that we can compensate.-->
            <!--So either do own project management or have one that has an api that allows you to access-->
            <!--what people do.-->
        <!--</p>-->

        <!--&lt;!&ndash; Connect account to github. Ask user to log into github. Then that github username or ID is-->
             <!--linked to the groupRoots account. So we can now track contributions &ndash;&gt;-->
        <!--<a title="GitHub" class="socialaccount_provider github" href="/accounts/github/login/?process=login">Connect account to GitHub</a><br/>-->

        <!--&lt;!&ndash; else &ndash;&gt;-->
        <!--&lt;!&ndash;<a href="{% url 'org_work:CreateGitRepo' organization.id project.id %}">Integrate Git (Not Now)</a><br/>&ndash;&gt;-->
        <!--<a href="{% url 'org_work:ConnectGitHub' organization.id project.id %}">Integrate GitHub</a><br/>-->
        <!--<a href="">Connect existing GitHub repository</a><br/>-->


        <!--<a onclick="openGITURL()">Go to Repository</a>-->

        <!--<script>-->
            <!--function openGITURL()-->
            <!--{-->
                <!--var URL;-->
                <!--$.ajax(-->
                <!--{-->
                    <!--'async': false,-->
                    <!--'url': "{% url 'org_work:getGitURL' organization.id organization.organization_name project.id project.project_name %}",-->
                    <!--'success': function (data) {-->
                        <!--URL = data;-->
                    <!--}-->
                <!--});-->
                <!--window.open(URL);-->

            <!--}-->
        <!--</script>-->


    <!--</main>-->

{% endwith %}
{% endblock %}

org_work/templates/org_work/newProject.html
{% extends "home/base.html" %}
{% load static %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'org_work/new_project_style.css' %}" />
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <script>

        var expandCounter = 0;

        function addExpandButton(id,name)
        {
            subCategories = subCategoriesAndId(name);
            if (subCategoriesAndId(name)[0].length != 0)
            {
                document.getElementById(id).innerHTML += "<button id=\"exp" + id + "\" onclick=\"expand('" + id + "', '" + name + "')\">v</button></div>";
            }
        }

        function subCategoriesAndId(parent_name)
        {
            var subCategoryList = [];
            var subCategoryIdList = [];
            {% for category in categories_list %}
                if ("{{ category.parent }}" == parent_name)
                {
                    var c = "{{ category.category_name }}";
                    var id = "{{ category.id }}";
                    subCategoryList.push(c);
                    subCategoryIdList.push(id);
                }
            {% endfor %}
            return [subCategoryList,subCategoryIdList]
        }


        // returns true if user is in category

        // MAKE THIS ASYNCHRONOUS
        // https://codeburst.io/asynchronous-code-inside-an-array-loop-c5d704006c99
        // http://callbackhell.com/
        function userInCategory(category_id)
        {
            var resp = 0;
            $.ajax(
            {
                'async': false,
                'type': "POST",
                'global': false,
                'dataType': 'html',
                'url': "{% url 'org_home:userInCategory' %}",
                'data': {category_id:category_id},
                'success': function (data) {
                    resp = data;
                }
            });
            return parseInt(resp) === 1;
        }

        // Will expand to show the list of subcategories
        // if hasAccess is true, then all children of this category can be selected
        function expand(category_id,category,hasAccess)
        {
            if (hasAccess === undefined)
                hasAccess = false;

            subCategories = subCategoriesAndId(category);
            var subCategoryList = subCategories[0];
            var subCategoryIdList = subCategories[1];

            var newdiv = document.createElement('div');
            newdiv.id = "close" + category_id;

            var checkOnPage =  document.getElementById(newdiv.id);
            if (checkOnPage == null)
            {
                expandCounter++;
                for (c in subCategoryList)
                {
                    var id = subCategoryIdList[c];
                    var name = subCategoryList[c];
                    var url = "{% url 'org_home:individualCategory' organization_id=organization.id category_id=123 %}".replace("123", subCategoryIdList[c]);

                    // if the category has subcategories
                    if (subCategoriesAndId(name)[0].length != 0)
                    {
                        // user has permision to select category as parent. By being in category or by hasAccess
                        if(hasAccess || userInCategory(id))
                        {
                            newdiv.innerHTML += "<div style='margin-left:15px' id=" + id + ">\
                            <input onclick='changeSharedProjectsHTML()' title='" + expandCounter + "' type='checkbox' id='choice" + id + "' name='categoryCheckbox' value='" + id + "'/>\
                            <label>" + name + "</label>\
                            <button id=\"exp" + id + "\" onclick=\"expand('" + id + "', '" + name + "',true)\">v</button></div>";
                        }
                        else
                        {
                            newdiv.innerHTML += "<div style='margin-left:15px' id=" + id + ">\
                            <label style=\"padding-left: 22px\" id=\"notInCat\">" + name + "</label>\
                            <button id=\"exp" + id + "\" onclick=\"expand('" + id + "', '" + name + "',false)\">v</button></div>";
                        }
                    }
                    // if the category doesn't have subcategories... so missing expand button
                    else
                    {
                        if(hasAccess || userInCategory(id))
                        {
                            newdiv.innerHTML += "<div style='margin-left:15px' id=" + id + ">\
                            <input onclick='changeSharedProjectsHTML()' title='" + expandCounter + "' type='checkbox' id='choice" + id + "' name='categoryCheckbox' value='" + id + "'/>\
                            <label>" + name + "</label></div>";
                        }
                        else
                        {
                            newdiv.innerHTML += "<div style='margin-left:15px' id=" + id + ">\
                            <label style=\"padding-left: 22px\" id=\"notInCat\">" + name + "</label></div>";
                        }
                    }
                }

                // add button that contracts the subcategories
                document.getElementById(category_id).innerHTML += "<input id='closeButton" + category_id + "' type=button value='^' onclick=\"contract('" + category_id + "')\"/>";
                document.getElementById(category_id).appendChild(newdiv);

                // hide the expand button
                document.getElementById("exp" + category_id).style.display='none';
            }
        }

        function contract(divName){
            document.getElementById("close" + divName).remove();
            document.getElementById("closeButton" + divName).remove();
            document.getElementById("exp" + divName).style.display = '';
            }

        function selectCategory(categoryId){
            id = "choice" + categoryId;
            document.getElementById(id).setAttribute('checked','');
        }

        // get all selected categories
        function getSelectedCategories()
        {
            var checkedBoxes = document.querySelectorAll('input[name=categoryCheckbox]:checked');
            var numbChecked = checkedBoxes.length;
            var selectedIds = [];
            var selectedTreePostions = [];

            for(var i = 0; i < numbChecked; i++)
            {
                var obj = checkedBoxes[i];
                selectedIds.push(obj.value);
                selectedTreePostions.push(obj.title);
            }

            return [selectedIds,selectedTreePostions];
        }

        function getSharedProjects(commonProjects)
        {
            var selectedIds = getSelectedCategories()[0];
            var selectedTreePositions = getSelectedCategories()[1];
            var commonProjectsJson;
            if(selectedIds.length > 0)
            {
                $.ajax(
                {
                    'type': "POST",
                    'data': {'selectedIds':JSON.stringify(selectedIds),
                            'selectedTreePositions':JSON.stringify(selectedTreePositions),
                            'maxTreePositions':expandCounter},
                    'url': "{% url 'org_work:ProjectsInCommon' %}",
                    'success': function (data)
                    {
                        commonProjectsJson = JSON.parse(data);
                        commonProjects(commonProjectsJson)
                        // id is commonProjectsJson[0].pk
                        // name is commonProjectsJson[0].fields.project_name
                    }
                });
            }
        }

        function changeSharedProjectsHTML()
        {
            $("[id^='parentChoice_']").remove();
            // callback function
            getSharedProjects(function(commonProjects)
            {
                for(var i in commonProjects)
                {
                    document.getElementById("parentProject").innerHTML += "<div id='parentChoice_\" + commonProjects[i].pk + \"'>" +
                        "<input type='radio'  name='parent' value='" + commonProjects[i].pk +
                        "'/><label>" + commonProjects[i].fields.project_name + "</label></div>";
                }
            });
        }

    </script>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    {% if category == None %}
    <form action="{% url 'org_work:submitNewProject' organization.id %}" method="post">
    {% else %}
    <form action="{% url 'org_work:submitNewSubProject' organization.id category.id %}" method="post">
    {% endif %}
    {% csrf_token %}
        <div id="categorySelect">
            <h3>1. Choose Branches</h3>
            <!--<input onclick='getSharedProjects()' type="checkbox" name="categoryCheckbox" id="categoryChoice-1" value="-1"/><label>No Parent</label>-->
            {% if categories_list %}
                {% for category in categories_list %}

                    <!-- Doens't have a parent... "Executive" -->
                    {% if category.parent == None %}
                        <div id= {{ category.id }}>
                            <!-- User not in category -->
                            {% if user not in category.members.all %}
                                <label style="padding-left: 22px" id="notInCat">{{ category }}</label>
                                <script>addExpandButton('{{ category.id }}', '{{ category }}');</script>
                                <script >expand('{{ category.id }}', '{{ category }}', false);</script>
                            {% else %}
                                <input onclick='changeSharedProjectsHTML()' title='0' type="checkbox" id="choice{{ category.id }}" name="categoryCheckbox" value="{{ category.id }}"/>
                                <label>{{ category }}</label>
                                <script>addExpandButton('{{ category.id }}', '{{ category }}');</script>
                                <script >expand('{{ category.id }}', '{{ category }}', true);</script>
                            {% endif %}

                        </div>
                    {% endif %}
                {% endfor %}

            <!-- Expand till get to current page category -->
                {% for ancestor in ancestor_categories_list %}
                    <!-- Don't need addExpandButton here because it is automatically added when executive calls it and expand
                     adds it automatically. (No expand called on executive because it is the base so need to manually add it there) -->
                    <script>expand('{{ ancestor.id }}', '{{ ancestor }}',userInCategory( {{ ancestor.pk }} ));</script>
                {% endfor %}

                <script>selectCategory('{{ category.id }}')</script>
                <script>changeSharedProjectsHTML()</script>

            {% else %}
                <p>No categories are available.</p>
            {% endif %}
        </div>

        <div id="parentProject">
            <h3>2. Choose a parent project</h3>
            <h6 style="text-align: center">Selected branches' shared projects</h6>
            <input type="radio" name="parent" id="noParent" value="-1"/><label>      No Parent</label>
        </div>

        <div id="projectManagement">
            <h3>3. Choose a project management system</h3>
            <p>Default selected</p>
        </div>

        <div id="details">
            <h3>4. Details</h3>
            <div style="padding-left:10px;" id="forms">
                <label>Name: </label>
                <input type="text" name="new_project" id="new_project"/><br/><br/>
            </div>
            <input style="float:right;" type="submit" value="Submit"/>
        </div>
    </form>

{% endblock %}